import { useEffect, useRef, useState } from 'react';
import { cents, dateKey, type Data } from './core';
import { calculateVault, type Movement } from './vault';
import NavIcon from './NavIcon';
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
export default function CashPanel({data,save,busy,request}:{data:Data;save:(d:Data)=>Promise<boolean>;busy:boolean;request:{id:number;type:'deposit'|'balance'}|null}){
 const [edit,setEdit]=useState<Movement|'new'|null>(null),[error,setError]=useState('');const form=useRef<HTMLFormElement>(null);const cash=data.cash;
 useEffect(()=>{if(request)setEdit('new');},[request?.id]);useEffect(()=>{if(edit)form.current?.scrollIntoView({block:'center',behavior:'smooth'});},[edit,request?.id]);
 const today=dateKey();const result=cash?calculateVault({...cash,rates:[{date:cash.start,annual:0}]},data.expenses.filter(e=>e.source==='cash'),today):null;
 const amount=(s:string)=>Number(s)===0&&s.trim()!==''?0:cents(s);
 return <>{error&&<p className="alert" role="alert">{error}</p>}{!cash?<form className="card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const opening=amount(String(f.get('amount')));if(await save({...data,cash:{opening,start:today,rates:[{date:today,annual:0}],movements:[]}}))setError('');}catch(x){setError((x as Error).message);}}}><h2>Tu billetera</h2><label>Efectivo que tienes hoy · MXN<input name="amount" type="number" min="0" step="0.01" inputMode="decimal" required/></label><p className="hint">Los gastos de efectivo de hoy también se descuentan.</p><button className="primary wide" disabled={busy}>Guardar saldo inicial</button></form>:<><section className="balance balance-current"><div className="balance-top"><span className="saldo-label"><NavIcon name="cash"/> Mi billetera</span><span className="pill">Efectivo</span></div><div className="current-value"><p>Saldo actual</p><h2>{money(result!.balance)}<small> MXN</small></h2></div><div className="balance-bottom"><span>Sin rendimientos</span><span>{today}</span></div></section>{result!.lowest<0&&<p className="alert">El efectivo quedó negativo. Revisa tus entradas y gastos.</p>}
 {edit&&<form ref={form} className="card" key={edit==='new'?'new-'+request?.id:edit.id} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const m:Movement={id:edit==='new'?crypto.randomUUID():edit.id,date:String(f.get('date')),amount:amount(String(f.get('amount'))),type:f.get('type') as Movement['type'],note:String(f.get('note')).trim()};if(m.date<cash.start||m.date>today)throw new Error('Selecciona una fecha entre el inicio y hoy.');if(m.type==='deposit'&&m.amount===0)throw new Error('La entrada debe ser mayor a cero.');if(m.type==='balance'&&cash.movements.some(x=>x.type==='balance'&&x.date===m.date&&x.id!==m.id))throw new Error('Ya hay un ajuste para ese día. Edítalo en el historial.');if(await save({...data,cash:{...cash,movements:[...cash.movements.filter(x=>x.id!==m.id),m]}})){setEdit(null);setError('');}}catch(x){setError((x as Error).message);}}}><h2>Movimiento de efectivo</h2><label>Tipo<select name="type" defaultValue={edit==='new'?request?.type:edit.type}><option value="deposit">Entrada de efectivo</option><option value="balance">Ajustar saldo de billetera</option></select></label><label>Importe · MXN<input name="amount" type="number" min="0" step="0.01" inputMode="decimal" required defaultValue={edit==='new'?'':edit.amount/100}/></label><label>Fecha<input name="date" type="date" min={cash.start} max={today} defaultValue={edit==='new'?today:edit.date} required/></label><label>Nota<input name="note" maxLength={200} defaultValue={edit==='new'?'':edit.note}/></label><div className="actions"><button disabled={busy} className="primary">Guardar</button><button type="button" onClick={()=>setEdit(null)}>Cancelar</button></div></form>}
 <div className="two"><section className="card"><span className="muted">Entradas</span><h3>{money(result!.deposits)}</h3></section><section className="card"><span className="muted">Gastos en efectivo</span><h3>{money(result!.spending)}</h3></section></div><section className="card"><h2>Entradas y ajustes</h2>{!cash.movements.length&&<p className="muted">Sin movimientos todavía.</p>}{[...cash.movements].sort((a,b)=>b.date.localeCompare(a.date)).map(m=><div className="vault-row" key={m.id}><button className="expense" disabled={busy} onClick={()=>setEdit(m)}><span className="expense-copy"><strong>{m.note||(m.type==='deposit'?'Entrada de efectivo':'Ajuste de saldo')}</strong><small>{m.date}</small></span><strong>{money(m.amount)}</strong></button><button disabled={busy} aria-label="Eliminar movimiento de efectivo" onClick={()=>{if(confirm('¿Eliminar este movimiento de efectivo?'))save({...data,cash:{...cash,movements:cash.movements.filter(x=>x.id!==m.id)}});}}><NavIcon name="close"/></button></div>)}</section><p className="hint">Los gastos están en Gastos y resumen. El efectivo se registra por separado; añadir una entrada aquí no descuenta automáticamente la Cajita.</p></>}</>;
}
