import { useEffect, useRef, useState } from 'react';
import { cents, dateKey, type Data, type Expense } from './core';
import { calculateVault, type Movement } from './vault';
import NavIcon from './NavIcon';
import BalanceEffect from './BalanceEffect';
import { accountHistory } from './accountHistory';
import MovementEditDialog from './MovementEditDialog';
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
export default function CashPanel({data,save,busy,request,onEditExpense}:{data:Data;onEditExpense:(e:Expense)=>void;save:(d:Data)=>Promise<boolean>;busy:boolean;request:{id:number;type:'deposit'|'balance'}|null}){
 const [edit,setEdit]=useState<Movement|'new'|null>(null),[depositToEdit,setDepositToEdit]=useState<Movement|null>(null),[error,setError]=useState(''),[showAllMovements,setShowAllMovements]=useState(false);const form=useRef<HTMLFormElement>(null);const cash=data.cash;
 useEffect(()=>{if(request)setEdit('new');},[request?.id]);useEffect(()=>{if(edit)form.current?.scrollIntoView({block:'center',behavior:'smooth'});},[edit,request?.id]);
 const today=dateKey();const history=accountHistory(data,'cash',today);const visibleHistory=showAllMovements?history:history.slice(0,5);const result=cash?calculateVault({...cash,rates:[{date:cash.start,annual:0}]},data.expenses.filter(e=>e.source==='cash'),today):null;
 const amount=(s:string)=>Number(s)===0&&s.trim()!==''?0:cents(s);
 return <>{error&&<p className="alert" role="alert">{error}</p>}{!cash?<form className="card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const opening=amount(String(f.get('amount')));if(await save({...data,cash:{opening,start:today,rates:[{date:today,annual:0}],movements:[]}}))setError('');}catch(x){setError((x as Error).message);}}}><h2>Tu billetera</h2><label>Efectivo que tienes hoy · MXN<input name="amount" type="number" min="0" step="0.01" inputMode="decimal" required/></label><p className="hint">Los gastos de efectivo de hoy también se descuentan.</p><button className="primary wide" disabled={busy}>Guardar saldo inicial</button></form>:<><section className="balance balance-current"><div className="balance-top"><span className="saldo-label"><NavIcon name="cash"/> Mi billetera</span><span className="pill">Efectivo</span></div><div className="current-value"><BalanceEffect balance={result!.balance}/><p>Saldo actual</p><h2 className="balance-number" key={result!.balance}>{money(result!.balance)}<small> MXN</small></h2></div><div className="balance-bottom"><span>Sin rendimientos</span><span>{today}</span></div><button className="balance-adjust" aria-label="Ajustar saldo completo" title="Ajustar saldo completo" disabled={busy} onClick={()=>setEdit('new')}><NavIcon name="balance"/></button></section>{result!.lowest<0&&<p className="alert">El efectivo quedó negativo. Revisa tus entradas y gastos.</p>}
 {edit&&<form ref={form} className="card" key={edit==='new'?'new-'+request?.id:edit.id} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const m:Movement={id:edit==='new'?crypto.randomUUID():edit.id,date:String(f.get('date')),amount:amount(String(f.get('amount'))),type:f.get('type') as Movement['type'],note:String(f.get('note')).trim()};if(m.date<cash.start||m.date>today)throw new Error('Selecciona una fecha entre el inicio y hoy.');if(m.type==='deposit'&&m.amount===0)throw new Error('La entrada debe ser mayor a cero.');if(m.type==='balance'&&cash.movements.some(x=>x.type==='balance'&&x.date===m.date&&x.id!==m.id))throw new Error('Ya hay un ajuste para ese día. Edítalo en el historial.');if(await save({...data,cash:{...cash,movements:[...cash.movements.filter(x=>x.id!==m.id),m]}})){setEdit(null);setError('');}}catch(x){setError((x as Error).message);}}}><h2>{edit==='new'?'Ajustar saldo completo':'Editar movimiento'}</h2><label>Tipo<select name="type" defaultValue={edit==='new'?'balance':edit.type}>{edit!=='new'&&<option value="deposit">Entrada de efectivo</option>}<option value="balance">Ajustar saldo de billetera</option></select></label><label>Importe · MXN<input name="amount" type="number" min="0" step="0.01" inputMode="decimal" required defaultValue={edit==='new'?'':edit.amount/100}/></label><label>Fecha<input name="date" type="date" min={cash.start} max={today} defaultValue={edit==='new'?today:edit.date} required/></label><label>Nota<input name="note" maxLength={200} defaultValue={edit==='new'?'':edit.note}/></label><div className="actions"><button disabled={busy} className="primary">Guardar</button><button type="button" onClick={()=>setEdit(null)}>Cancelar</button>{edit!=='new'&&<button className="danger" type="button" disabled={busy} onClick={async()=>{if(confirm('¿Eliminar este movimiento de efectivo? ')&&await save({...data,cash:{...cash,movements:cash.movements.filter(x=>x.id!==edit.id)}}))setEdit(null);}}>Eliminar movimiento</button>}</div></form>}
 <div className="two"><section className="card"><span className="muted">Entradas</span><h3>{money(result!.deposits)}</h3></section><section className="card"><span className="muted">Gastos en efectivo</span><h3>{money(result!.spending)}</h3></section></div><section className="card"><h2>Movimientos de efectivo</h2>{!history.length&&<p className="muted">Sin movimientos todavía.</p>}{visibleHistory.map(entry=>entry.kind==='expense'?<div className="vault-row" key={'expense-'+entry.value.id}><button className="expense" disabled={busy} onClick={()=>onEditExpense(entry.value)}><span className="category-icon outgoing"><NavIcon name="outgoing"/></span><span className="expense-copy"><strong>{entry.value.note||entry.value.category}</strong><small>{entry.value.date} · Gasto · {entry.value.category}</small></span><strong>−{money(entry.value.amount)}</strong></button></div>:((m)=><div className="vault-row" key={m.id}><button className="expense" disabled={busy} onClick={()=>m.type==='deposit'?setDepositToEdit(m):setEdit(m)}><span className={'category-icon '+(m.type==='deposit'?'incoming':'adjustment')}><NavIcon name={m.type==='deposit'?'incoming':'balance'}/></span><span className="expense-copy"><strong>{m.note||(m.type==='deposit'?'Entrada de efectivo':'Ajuste de saldo')}</strong><small>{m.date}</small></span><strong>{m.type==='deposit'?'+':''}{money(m.amount)}</strong></button></div>)(entry.value))}{history.length>5&&<button className="show-all-movements" onClick={()=>setShowAllMovements(value=>!value)}>{showAllMovements?'Ver menos':'Ver todos'}</button>}</section><MovementEditDialog movement={depositToEdit} account="cash" data={data} busy={busy} save={save} onClose={()=>setDepositToEdit(null)}/></>}</>;
}





