import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { cents, dateKey, initial, parseBackup, period, validDate, type Data, type Expense } from './core';
import { read, write } from './db';
import '@fontsource-variable/jetbrains-mono/wght.css';
import '@fontsource/silkscreen/latin-400.css';
import '@fontsource/silkscreen/latin-700.css';
import './style.css';
import VaultPanel from './VaultPanel';
import CashPanel from './CashPanel';
import NavIcon from './NavIcon';
import BrandMark from './BrandMark';
import DepositDialog from './DepositDialog';
const categoryIcon=(c:string)=>({Comida:'food',Transporte:'transport',Compras:'shopping',Servicios:'ajustes',Salud:'health',Ocio:'leisure'}[c]||'other');
const money = (n: number) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
const human = (s: string) => new Date(s+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short'});
function App() {
 const [data,setData]=useState<Data>(initial), [ready,setReady]=useState(false), [error,setError]=useState(''), [notice,setNotice]=useState(''), [busy,setBusy]=useState(false), [tab,setTab]=useState('cajita'), [offset,setOffset]=useState(0), [cadence]=useState<'week'>('week'), [editor,setEditor]=useState<Expense | 'new' | null>(null), [online,setOnline]=useState(navigator.onLine), [offlineReady,setOfflineReady]=useState(false);
 const [movementRequest,setMovementRequest]=useState<{id:number;type:'deposit'|'withdrawal'|'balance'}|null>(null);
 const [account,setAccount]=useState<'vault'|'cash'>('vault');
 const [cashRequest,setCashRequest]=useState<{id:number;type:'deposit'|'balance'}|null>(null);
 const [depositOpen,setDepositOpen]=useState(false);
 const actionDialog=useRef<HTMLDialogElement>(null);
 const dialog=useRef<HTMLDialogElement>(null); const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{read().then(d=>{setData(d);setReady(true);}).catch(()=>setError('No se pudo abrir el almacenamiento local. Prueba de nuevo en Safari, fuera de navegación privada.')); const listener=()=>setOnline(navigator.onLine); window.addEventListener('online',listener);window.addEventListener('offline',listener); return ()=>{window.removeEventListener('online',listener);window.removeEventListener('offline',listener);};},[]);
 useEffect(()=>{if(editor) dialog.current?.showModal(); else dialog.current?.close();},[editor]);
 useEffect(()=>{ if ('serviceWorker' in navigator && import.meta.env.PROD) navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>setOfflineReady(true)).catch(()=>setNotice('El modo sin conexión aún no está disponible. Recarga con internet.')); },[]);
 async function save(next: Data) { setBusy(true);setError('');try { await write(next);setData(next);return true; } catch { setError('No se pudo guardar. Tu cambio no se aplicó. Revisa el espacio disponible e intenta otra vez.');return false;} finally {setBusy(false);} }
 const p=period(cadence,offset); const expenses=data.expenses.filter(e=>e.date>=p.start && e.date<p.end).sort((a,b)=>b.date.localeCompare(a.date)); const spent=expenses.reduce((n,e)=>n+e.amount,0);
 async function submitExpense(event: React.FormEvent<HTMLFormElement>) {event.preventDefault();const f=new FormData(event.currentTarget);try{const date=String(f.get('date'));if(!validDate(date)) throw new Error('Selecciona una fecha válida.');const e: Expense={id:editor==='new'?crypto.randomUUID():(editor as Expense).id,amount:cents(String(f.get('amount'))),date,category:String(f.get('category')),note:String(f.get('note')).trim(),source:f.get('source') as 'vault'|'cash'};if(await save({...data,expenses:[...data.expenses.filter(x=>x.id!==e.id),e]})){setEditor(null);setNotice('Gasto guardado.');}}catch(e){setError((e as Error).message);} }
 async function remove(e: Expense) {if(confirm(`¿Eliminar ${e.note || e.category} (${money(e.amount)})?`) && await save({...data,expenses:data.expenses.filter(x=>x.id!==e.id)})){setEditor(null);setNotice('Gasto eliminado.');}}
 function exportData() {const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`pocketlimit-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setNotice('Respaldo generado. Guárdalo en Archivos.');}
 async function importData(f?: File) {if(!f)return;try{if(f.size>20*1024*1024)throw new Error('El archivo es demasiado grande (máximo 20 MB).');const next=parseBackup(await f.text());if(confirm(`Restaurar ${next.expenses.length} gastos${next.vault ? " y tu Cajita" : " (sin Cajita)"} reemplazará todos los datos actuales. ¿Continuar?`)){if(await save(next)){setOffset(0);setNotice('Respaldo restaurado.');}}}catch(e){setError((e as Error).message);}finally{if(file.current)file.current.value='';}}
 const edit=editor && editor!=='new'?editor:null;
 return <div className="shell"><header><a href="#" className="brand" onClick={()=>setTab('cajita')}><span className="logo"><BrandMark/></span>PocketLimit</a><span className="private"><NavIcon name="lock"/> Solo en tu dispositivo</span></header>
 <main><div className="intro compact-intro">{tab!=='cajita' && <h1>{tab==='gastos'?'Gastos y resumen':tab==='cash'?'Efectivo':'Ajustes'}</h1>}</div>
 {error && <div role="alert" className="alert">{error}</div>}{notice && <div role="status" className="notice">{notice}<button aria-label="Cerrar mensaje" onClick={()=>setNotice('')}><NavIcon name="close"/></button></div>}
 {!ready ? <section className="card"><p>{error?'Tus datos no se han cargado.':'Abriendo tu bolsillo…'}</p><button onClick={()=>location.reload()}>Reintentar</button></section> : <>
 {tab==='gastos' && <div className="period"><button aria-label="Periodo anterior" onClick={()=>setOffset(offset-1)}><NavIcon name="left"/></button><div><strong>Gastos de la semana</strong><small>{human(p.start)} — {human(p.last)}{offset===0?' · Actual':''}</small></div><button aria-label="Periodo siguiente" onClick={()=>setOffset(offset+1)}><NavIcon name="right"/></button>{offset!==0 && <button onClick={()=>setOffset(0)}>Hoy</button>}</div>}
 {tab==='cash' && <CashPanel data={data} save={save} busy={busy} request={cashRequest}/>} 
 {tab==='cajita' && <VaultPanel data={data} save={save} busy={busy} request={movementRequest} onEditExpense={setEditor}/>} 
 {tab==='gastos' && <section className="card list">{expenses.length===0?<div className="empty"><span><NavIcon name="gastos"/></span><h3>Un nuevo comienzo</h3><p>Registra un gasto y empieza a ver a dónde va tu dinero.</p></div>:expenses.map(e=><button disabled={busy} key={e.id} className="expense" onClick={()=>setEditor(e)}><span className="category-icon"><NavIcon name={categoryIcon(e.category)}/></span><span className="expense-copy"><strong>{e.note||e.category}</strong><small>{e.category} · {human(e.date)} · {e.source==='cash'?'Efectivo':'Cajita'}</small></span><strong>{money(e.amount)}</strong><span className="muted"><NavIcon name="right"/></span></button>)}<p className="hint">Toca un gasto para editarlo o eliminarlo.</p></section>}
 {tab==='gastos' && <><div className="two"><section className="card"><span className="muted">Total gastado</span><h3>{money(spent)}</h3></section><section className="card"><span className="muted">Gastos registrados</span><h3>{expenses.length}</h3></section></div><section className="card"><h2>Por categoría</h2>{spent===0?<p className="muted">Tus estadísticas aparecerán al registrar gastos.</p>:data.settings.categories.map(c=>({c,total:expenses.filter(e=>e.category===c).reduce((n,e)=>n+e.amount,0)})).filter(x=>x.total>0).sort((a,b)=>b.total-a.total).map(x=><div className="stat" key={x.c}><div><span>{x.c}</span><strong>{money(x.total)} <small>· {Math.round(x.total/spent*100)}%</small></strong></div><div className="progress"><span style={{width:`${x.total/spent*100}%`}} /></div></div>)}</section><section className="card"><h2>Últimas 6 semanas</h2>{Array.from({length:6},(_,i)=>{const r=period(cadence,offset-i);const n=data.expenses.filter(e=>e.date>=r.start&&e.date<r.end).reduce((t,e)=>t+e.amount,0);return <div className="history" key={r.start}><span>{human(r.start)} — {human(r.last)}</span><strong>{money(n)}</strong></div>;})}</section></>}
 {tab==='ajustes' && <><section className="card"><h2>Categorías</h2><div className="chips">{data.settings.categories.map(c=><span key={c}>{c}<button disabled={busy||data.settings.categories.length===1||data.expenses.some(e=>e.category===c)} aria-label={`Eliminar categoría ${c}`} onClick={()=>save({...data,settings:{...data.settings,categories:data.settings.categories.filter(x=>x!==c)}})}><NavIcon name="close"/></button></span>)}</div><form className="inline" onSubmit={async ev=>{ev.preventDefault();const form=ev.currentTarget;const c=String(new FormData(form).get('category')).trim();if(!c || data.settings.categories.some(x=>x.toLowerCase()===c.toLowerCase())){setError('Escribe una categoría nueva.');return;}if(data.settings.categories.length>=50){setError('Máximo 50 categorías.');return;}if(await save({...data,settings:{...data.settings,categories:[...data.settings.categories,c]}}))form.reset();}}><input aria-label="Nueva categoría" name="category" maxLength={40} placeholder="Nueva categoría" required/><button disabled={busy}>Añadir</button></form><p className="hint">Las categorías con gastos se conservan para proteger tu historial.</p></section><section className="card"><h2>Respaldo y privacidad</h2><p className="muted">Todo se guarda en este navegador con IndexedDB. No hay cuentas, anuncios ni envío de gastos a servidores.</p><div className="actions"><button onClick={exportData}><NavIcon name="download"/> Exportar JSON</button><button disabled={busy} onClick={()=>file.current?.click()}><NavIcon name="upload"/> Restaurar JSON</button></div><input hidden type="file" ref={file} accept=".json,application/json" onChange={e=>importData(e.target.files?.[0])}/><p className="hint">Guarda respaldos regularmente. Borrar datos de Safari, cambiar de dispositivo o de dirección web puede dejarte sin tu historial. El JSON contiene tus gastos sin cifrar.</p></section><section className="card"><h2>En tu iPhone</h2><p className="muted">Abre PocketLimit en Safari → Compartir → Añadir a pantalla de inicio → Abrir como app web, si aparece → Añadir.</p><p className="hint">{online?'Con internet':'Sin internet'} · {offlineReady?'Modo sin conexión listo':'Abre la versión publicada con internet para preparar el modo sin conexión'}.</p></section></>}
  </>}</main><nav className="bottom-dock" aria-label="Navegación principal">{[['cajita','◈','Cajita'],['gastos','▥','Gastos'],['add','$','Añadir movimiento'],['cash','▣','Efectivo'],['ajustes','⚙','Ajustes']].map(([id,icon,label])=>id==='add'?<button key={id} className="dock-add" aria-label="Añadir movimiento" disabled={!ready||busy} onClick={()=>{setAccount(tab==='cash'?'cash':'vault');actionDialog.current?.showModal();}}><NavIcon name="dollar"/></button>:<button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined}><NavIcon name={id}/>{label}</button>)}</nav>
 <dialog ref={actionDialog} className="movement-picker" aria-labelledby="movement-title"><div className="section-title"><h2 id="movement-title">Movimiento</h2><button aria-label="Cerrar menú" onClick={()=>actionDialog.current?.close()}><NavIcon name="close"/></button></div><div className="account-switch" aria-label="Cuenta del movimiento"><button aria-pressed={account==='vault'} className={account==='vault'?'selected':''} onClick={()=>setAccount('vault')}><NavIcon name="cajita"/> Mi Cajita</button><button aria-pressed={account==='cash'} className={account==='cash'?'selected':''} onClick={()=>setAccount('cash')}><NavIcon name="cash"/> Billetera</button></div><div className="movement-options"><button onClick={()=>{actionDialog.current?.close();setEditor('new');}}><b className="movement-icon outgoing"><NavIcon name="outgoing"/></b><span>Gasto</span></button><button disabled={!data[account]} onClick={()=>{actionDialog.current?.close();setDepositOpen(true);}}><b className="movement-icon incoming"><NavIcon name="incoming"/></b><span>Depósito</span></button></div>{!data[account]&&<p className="hint">Configura primero el saldo de {account==='cash'?'tu billetera':'Mi Cajita'}.</p>}</dialog>{depositOpen&&<DepositDialog data={data} account={account} busy={busy} save={save} onClose={()=>setDepositOpen(false)}/>}  <dialog ref={dialog} onCancel={()=>{setEditor(null);setError('');}}><form key={editor==='new'?'new':edit?.id} onSubmit={submitExpense}><div className="section-title"><h2>{edit?'Editar gasto':'Nuevo gasto'}</h2><button type="button" aria-label="Cerrar" onClick={()=>{setEditor(null);setError('');}}><NavIcon name="close"/></button></div>{error && <p role="alert" className="alert">{error}</p>}<label>Importe · MXN<input autoFocus name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" placeholder="0.00" required defaultValue={edit?edit.amount/100:''}/></label><label>Pagar desde<select name="source" defaultValue={edit?.source||account}><option value="vault">Cajita</option><option value="cash">Efectivo</option></select></label><label>Categoría<select name="category" defaultValue={edit?.category}>{data.settings.categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Fecha<input type="date" name="date" required defaultValue={edit?.date||dateKey()}/></label><label>Nota opcional<input name="note" maxLength={200} placeholder="¿En qué lo gastaste?" defaultValue={edit?.note}/></label><button className="primary wide" disabled={busy}>{busy?'Guardando…':'Guardar gasto'}</button>{edit && <button className="danger wide" disabled={busy} type="button" onClick={()=>remove(edit)}>Eliminar gasto</button>}</form></dialog></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);












