import { useEffect, useRef, useState } from 'react';
import { cents, dateKey, type Data } from './core';
import type { Movement } from './vault';
import NavIcon from './NavIcon';

export default function MovementEditDialog({movement,account,data,busy,save,onClose}:{movement:Movement|null;account:'vault'|'cash';data:Data;busy:boolean;save:(data:Data)=>Promise<boolean>;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [error,setError]=useState('');
 useEffect(()=>{if(movement)dialog.current?.showModal();else dialog.current?.close();},[movement]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!movement)return;const form=new FormData(event.currentTarget);try{const amount=cents(String(form.get('amount'))),date=String(form.get('date')),note=String(form.get('note')||'').trim(),accountData=data[account];if(!accountData)throw new Error('No se encontró el saldo de esta cuenta.');if(date<accountData.start||date>dateKey())throw new Error('La fecha debe estar entre el inicio y hoy.');if(amount<=0)throw new Error('El importe debe ser mayor a cero.');if(await save({...data,[account]:{...accountData,movements:accountData.movements.map(item=>item.id===movement.id?{...item,amount,date,note}:item)}})){setError('');onClose();}}catch(e){setError((e as Error).message);}}
 async function remove(){if(!movement)return;const accountData=data[account];if(!accountData)return;if(confirm('¿Eliminar este depósito?')&&await save({...data,[account]:{...accountData,movements:accountData.movements.filter(item=>item.id!==movement.id)}}))onClose();}
 return <dialog ref={dialog} onCancel={onClose} aria-labelledby="edit-deposit-title"><form onSubmit={submit}><div className="section-title"><h2 id="edit-deposit-title">Editar depósito</h2><button type="button" aria-label="Cerrar" onClick={onClose}><NavIcon name="close"/></button></div>{error&&<p className="alert" role="alert">{error}</p>}<label>Importe · MXN<input autoFocus name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" required defaultValue={movement?movement.amount/100:''}/></label><label>Fecha<input name="date" type="date" min={data[account]?.start} max={dateKey()} required defaultValue={movement?.date}/></label><label>Nota opcional<input name="note" maxLength={200} placeholder="¿De dónde vino el depósito?" defaultValue={movement?.note||''}/></label><button className="primary wide" disabled={busy}>{busy?'Guardando…':'Guardar depósito'}</button><button className="danger wide" type="button" disabled={busy} onClick={remove}>Eliminar depósito</button></form></dialog>;
}
