import { useEffect, useRef, useState } from 'react';
import { cents, dateKey, type Data, type Expense } from './core';
import { calculateVault, validateVault, type Movement } from './vault';
import NavIcon from './NavIcon';
import BalanceEffect from './BalanceEffect';
import { accountHistory } from './accountHistory';
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
const dateLabel=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'});
export default function VaultPanel({data,save,busy,request,onEditExpense}:{data:Data;onEditExpense:(e:Expense)=>void;save:(d:Data)=>Promise<boolean>;busy:boolean;request:{id:number;type:Movement['type']}|null}){
 const [message,setMessage]=useState(''),[editing,setEditing]=useState<Movement|'new'|null>(null),[today,setToday]=useState(dateKey()); const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const r=()=>setToday(dateKey());window.addEventListener('focus',r);return()=>window.removeEventListener('focus',r);},[]); useEffect(()=>{if(request)setEditing('new');},[request?.id]); useEffect(()=>{if(editing)form.current?.scrollIntoView({behavior:'smooth',block:'center'});},[editing]);
 const v=data.vault; const history=accountHistory(data,'vault',today); const result=v?calculateVault(v,data.expenses.filter(e=>e.source!=='cash'),today):null;
 async function persist(next:Data){try{if(next.vault)validateVault(next.vault);if(await save(next)){setMessage('Cajita actualizada.');return true;}}catch(e){setMessage((e as Error).message);}return false;}
 function amount(s:string){return Number(s)===0&&s.trim()!==''?0:cents(s);} function check(s:string,start='2000-01-01'){if(s<start||s>today)throw Error('La fecha debe estar entre el inicio y hoy.');return s;}
 return <>{message&&<p className="notice">{message}</p>}{!v?<form className="card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const start=check(String(f.get('start')||today));await persist({...data,vault:{opening:amount(String(f.get('opening'))),start,rates:[{date:start,annual:Number(f.get('annual'))}],movements:[]}});}catch(x){setMessage((x as Error).message);}}}><h2>Empieza con tu saldo actual</h2><label>Saldo inicial · MXN<input name="opening" type="number" min="0" step="0.01" required/></label><label>Fecha de inicio<input type="date" name="start" max={today} defaultValue={today}/></label><label>Tasa anual · %<input name="annual" type="number" min="0" max="100" step="0.01" defaultValue="13" required/></label><button className="primary wide">Activar mi Cajita</button></form>:<>
 <section className={`balance balance-current ${result!.balance<0?'over':''}`}><div className="balance-top"><span className="saldo-label"><span className="saldo-symbol"><NavIcon name="cajita"/></span> Mi Cajita Turbo</span><span className="pill">{result!.annual.toFixed(2)}% anual</span></div><div className="current-value"><BalanceEffect balance={result!.balance}/><p>Saldo estimado</p><h2 className="balance-number">{money(result!.balance)}<small> MXN</small></h2></div><div className="balance-bottom"><span>MXN</span><span>{dateLabel(today)}</span></div><button className="balance-adjust" aria-label="Ajustar saldo completo" onClick={()=>setEditing('new')}><NavIcon name="balance"/></button></section><div className="two"><section className="card"><span className="muted">Rendimiento acumulado</span><h3>{money(result!.interest)}</h3></section><section className="card"><span className="muted">Estimado mañana</span><h3>+{money(result!.tomorrow)}</h3></section></div>
 {editing&&<form ref={form} className="card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const date=check(String(f.get('date')),v.start),type=f.get('type') as Movement['type'],m:Movement={id:editing==='new'?crypto.randomUUID():editing.id,date,type,amount:amount(String(f.get('amount'))),note:String(f.get('note')||'').trim()};if(m.type==='balance'&&v.movements.some(x=>x.type==='balance'&&x.date===m.date&&x.id!==m.id))throw Error('Ya existe un ajuste para esa fecha. Edítalo en el historial.');const change=editing==='new'&&f.get('changeRate')==='on',annual=Number(f.get('annual'));if(change&&(!Number.isFinite(annual)||annual<0||annual>100))throw Error('La tasa debe estar entre 0 y 100%.');const rates=change?[...v.rates.filter(r=>r.date!==date),{date,annual}]:v.rates;if(await persist({...data,vault:{...v,rates,movements:[...v.movements.filter(x=>x.id!==m.id),m]}}))setEditing(null);}catch(x){setMessage((x as Error).message);}}}><h2>{editing==='new'?'Ajustar saldo completo':'Editar movimiento'}</h2><label>Tipo<select name="type" defaultValue={editing==='new'?(request?.type||'balance'):editing.type}>{editing!=='new'&&<option value="deposit">Depósito · dinero que entra</option>}{editing!=='new'&&editing.type==='withdrawal'&&<option value="withdrawal">Retiro anterior</option>}<option value="balance">Ajustar al saldo real de Nu</option></select></label><label>Importe o saldo real · MXN<input name="amount" type="number" min="0" step="0.01" required defaultValue={editing==='new'?'':editing.amount/100}/></label><label>Fecha<input type="date" name="date" min={v.start} max={today} defaultValue={editing==='new'?today:editing.date} required/></label><label>Nota opcional<input name="note" defaultValue={editing==='new'?'':editing.note}/></label>{editing==='new'&&<><label className="check-row"><input type="checkbox" name="changeRate"/> Cambiar tasa anual también</label><label>Tasa anual · %<input name="annual" type="number" min="0" max="100" step="0.01" defaultValue={result!.annual}/></label></>}<div className="actions"><button className="primary" disabled={busy}>Guardar movimiento</button><button type="button" onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
 <section className="card"><h2>Movimientos</h2>{!history.length&&<p className="muted">Sin movimientos todavía.</p>}{history.map(entry=>entry.kind==='expense'?<div className="vault-row" key={'expense-'+entry.value.id}><button className="expense" disabled={busy} onClick={()=>onEditExpense(entry.value)}><span className="category-icon"><NavIcon name="outgoing"/></span><span className="expense-copy"><strong>{entry.value.note||entry.value.category}</strong><small>{dateLabel(entry.value.date)} · Gasto · {entry.value.category}</small></span><strong>−{money(entry.value.amount)}</strong></button></div>:((m)=><div className="vault-row" key={m.id}><button className="expense" disabled={busy} onClick={()=>setEditing(m)}><span className="category-icon"><NavIcon name={m.type==='deposit'?'incoming':m.type==='withdrawal'?'outgoing':'balance'}/></span><span className="expense-copy"><strong>{m.note||({deposit:'Depósito',withdrawal:'Retiro',balance:'Saldo real de Nu'}[m.type])}</strong><small>{dateLabel(m.date)} · Movimiento</small></span><strong>{m.type==='deposit'?'+':m.type==='withdrawal'?'−':''}{money(m.amount)}</strong></button><button aria-label="Eliminar movimiento" disabled={busy} onClick={()=>{if(confirm('¿Eliminar este movimiento? Se recalculará el saldo y el rendimiento.'))persist({...data,vault:{...v,movements:v.movements.filter(x=>x.id!==m.id)}});}}><NavIcon name="close"/></button></div>)(entry.value))}</section></>}
 </>;
}
