import { useEffect, useRef, useState } from 'react';
import { cents, dateKey, type Data, type Expense } from './core';
import { calculateVault, validateVault, type Movement } from './vault';
import NavIcon from './NavIcon';
import BalanceEffect from './BalanceEffect';
import { accountHistory } from './accountHistory';
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
const dateLabel=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'short',year:'numeric'});
export default function VaultPanel({data,save,busy,request,onEditExpense}:{data:Data;onEditExpense:(e:Expense)=>void;save:(d:Data)=>Promise<boolean>;busy:boolean;request:{id:number;type:Movement["type"]}|null}){
 const [message,setMessage]=useState(''),[editing,setEditing]=useState<Movement|'new'|null>(null),[today,setToday]=useState(dateKey());
 useEffect(()=>{const refresh=()=>setToday(dateKey());const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[]);
 const movementForm=useRef<HTMLFormElement>(null);
 useEffect(()=>{if(request){setEditing('new');setMessage('');}},[request?.id]);
 useEffect(()=>{if(editing)movementForm.current?.scrollIntoView({behavior:'smooth',block:'center'});},[editing,request?.id]);
 const v=data.vault;const history=accountHistory(data,'vault',today);const result=v?calculateVault(v,data.expenses.filter(e=>e.source!=='cash'),today):null;
 async function persist(next:Data){try{if(next.vault)validateVault(next.vault);if(await save(next)){setMessage('Cajita actualizada.');return true;}}catch(e){setMessage((e as Error).message);}return false;}
 function amount(s:string){return s==='0'||s==='0.00'?0:cents(s);}
 function checkDate(s:string,start='2000-01-01'){if(s<start||s>today)throw new Error('La fecha debe estar entre el inicio del seguimiento y hoy.');return s;}
 return <>{message&&<p role="status" className="notice">{message}</p>}
 {!v?<form className="card" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await persist({...data,vault:{opening:amount(String(f.get('opening'))),start:checkDate(String(f.get('start')||dateKey())),rates:[{date:String(f.get('start')||dateKey()),annual:Number(f.get('annual'))}],movements:[]}});}catch(x){setMessage((x as Error).message);}}}><h2>Empieza con tu saldo actual</h2><p className="muted">Copia el saldo que ves en Nu y la fecha de ese saldo. Desde esa fecha, los gastos se restan y los depósitos se suman.</p><label>Saldo inicial · MXN<input name="opening" type="number" min="0" step="0.01" inputMode="decimal" required placeholder="0.00"/></label><details className="start-date-option"><summary>Inicio: hoy · cambiar fecha</summary><label>Fecha de inicio<input type="date" name="start" min="2000-01-01" max={today} defaultValue={today}/></label></details><label>Tasa anual · %<input name="annual" type="number" inputMode="decimal" min="0" max="100" step="0.01" defaultValue="13" required/></label><p className="hint">Si introduces el saldo actual, evita registrar de nuevo gastos o depósitos ya incluidos en ese saldo. Los gastos de la fecha de inicio también se descuentan.</p><button className="primary wide" disabled={busy}>Activar mi Cajita</button></form>:<>
 <section className={`balance balance-current ${result!.balance<0?'over':''}`}><div className="balance-top"><span className="saldo-label"><span className="saldo-symbol"><NavIcon name="cajita"/></span> Mi Cajita Turbo</span><span className="pill">{result!.annual.toFixed(2)}% anual</span></div><div className="current-value"><BalanceEffect balance={result!.balance}/><p>Saldo estimado</p><h2 className="balance-number" key={result!.balance}>{money(result!.balance)}<small> MXN</small></h2></div><div className="balance-bottom"><span>MXN</span><span>{dateLabel(today)}</span></div><button className="balance-adjust" aria-label="Ajustar saldo completo" title="Ajustar saldo completo" disabled={busy} onClick={()=>setEditing('new')}><NavIcon name="balance"/></button></section><div className="two"><section className="card"><span className="muted">Rendimiento acumulado</span><h3>{money(result!.interest)}</h3></section><section className="card"><span className="muted">Estimado mañana</span><h3>+{money(result!.tomorrow)}</h3></section></div>
 {result!.lowest<0&&<p className="alert">Hay fechas con saldo negativo. Revisa el saldo inicial, los depósitos y los gastos; esos días no generan rendimiento.</p>}
 
 {editing&&<form ref={movementForm} className="card" key={editing==='new'?('new-'+request?.id):editing.id} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const m:Movement={id:editing==='new'?crypto.randomUUID():editing.id,date:checkDate(String(f.get('date')),v.start),type:f.get('type') as Movement['type'],amount:amount(String(f.get('amount'))),note:String(f.get('note')).trim()};if(m.type==='balance'&&v.movements.some(x=>x.type==='balance'&&x.date===m.date&&x.id!==m.id))throw new Error('Ya existe un ajuste para esa fecha. Edítalo en el historial.');if(await persist({...data,vault:{...v,movements:[...v.movements.filter(x=>x.id!==m.id),m]}}))setEditing(null);}catch(x){setMessage((x as Error).message);}}}><h2>{editing==='new'?'Ajustar saldo completo':'Editar movimiento'}</h2><label>Tipo<select name="type" defaultValue={editing==='new'?(request?.type||'balance'):editing.type}>{editing!=='new'&&<option value="deposit">Depósito · dinero que entra</option>}{editing!=='new'&&editing.type==='withdrawal'&&<option value="withdrawal">Retiro anterior</option>}<option value="balance">Ajustar al saldo real de Nu</option></select></label><label>Importe o saldo real · MXN<input name="amount" type="number" min="0" step="0.01" inputMode="decimal" required defaultValue={editing==='new'?'':editing.amount/100}/></label><label>Fecha<input name="date" type="date" min={v.start} max={today} required defaultValue={editing==='new'?today:editing.date}/></label><label>Nota opcional<input name="note" maxLength={200} defaultValue={editing==='new'?'':editing.note}/></label><p className="hint">El ajuste fija el saldo al cierre de la fecha elegida. Usa el saldo de Nu después de todos los movimientos de ese día.</p><div className="actions"><button disabled={busy} className="primary">Guardar movimiento</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancelar</button></div></form>}
 <details className="card"><summary>Desglose del saldo</summary>{[['Saldo inicial',v.opening],['Depósitos',result!.deposits],['Retiros',result!.withdrawals],['Gastos descontados',result!.spending],['Ajustes al saldo real',result!.adjustments]].map(([label,n])=><div key={label} className="history"><span>{label}</span><strong>{money(Number(n))}</strong></div>)}</details>
 <section className="card"><h2>Movimientos</h2>{!history.length&&<p className="muted">Sin movimientos todavía.</p>}{history.map(entry=>entry.kind==='expense'?<div className="vault-row" key={'expense-'+entry.value.id}><button className="expense" disabled={busy} onClick={()=>onEditExpense(entry.value)}><span className="category-icon"><NavIcon name="outgoing"/></span><span className="expense-copy"><strong>{entry.value.note||entry.value.category}</strong><small>{dateLabel(entry.value.date)} · Gasto · {entry.value.category}</small></span><strong>−{money(entry.value.amount)}</strong></button></div>:((m)=><div className="vault-row" key={m.id}><button className="expense" disabled={busy} onClick={()=>setEditing(m)}><span className="category-icon"><NavIcon name={m.type==='deposit'?'incoming':m.type==='withdrawal'?'outgoing':'balance'}/></span><span className="expense-copy"><strong>{m.note||({deposit:'Depósito',withdrawal:'Retiro',balance:'Saldo real de Nu'}[m.type])}</strong><small>{dateLabel(m.date)} · {{deposit:'Entrada',withdrawal:'Salida',balance:'Ajuste'}[m.type]}</small></span><strong>{m.type==='deposit'?'+':m.type==='withdrawal'?'−':''}{money(m.amount)}</strong></button><button aria-label={`Eliminar movimiento ${m.note||dateLabel(m.date)}`} disabled={busy} onClick={async()=>{if(confirm('¿Eliminar este movimiento? Se recalculará el saldo y el rendimiento.')&&await persist({...data,vault:{...v,movements:v.movements.filter(x=>x.id!==m.id)}}))setEditing(null);}}><NavIcon name="close"/></button></div>)(entry.value))}</section>
 <details className="card"><summary>Tasa y saldo inicial</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const date=checkDate(String(f.get('date')),v.start);const annual=Number(f.get('annual'));await persist({...data,vault:{...v,rates:[...v.rates.filter(r=>r.date!==date),{date,annual}]}});}catch(x){setMessage((x as Error).message);}}}><h2>Cambiar tasa desde una fecha</h2><label>Tasa anual · %<input type="number" name="annual" min="0" max="100" step="0.01" required defaultValue={result!.annual}/></label><label>Aplicar desde<input type="date" name="date" min={v.start} max={today} defaultValue={today} required/></label><button disabled={busy}>Guardar tasa</button></form>{[...v.rates].sort((a,b)=>a.date.localeCompare(b.date)).map(r=><div className="history" key={r.date}><span>{dateLabel(r.date)}</span><strong>{r.annual.toFixed(2)}%</strong>{r.date!==v.start&&<button disabled={busy} aria-label={`Eliminar tasa de ${r.date}`} onClick={()=>{if(confirm('¿Eliminar este cambio de tasa?'))persist({...data,vault:{...v,rates:v.rates.filter(x=>x.date!==r.date)}});}}><NavIcon name="close"/></button>}</div>)}<form onSubmit={async e=>{e.preventDefault();try{const opening=amount(String(new FormData(e.currentTarget).get('opening')));if(confirm('¿Corregir el saldo inicial y recalcular el historial?'))await persist({...data,vault:{...v,opening}});}catch(x){setMessage((x as Error).message);}}}><label>Corregir saldo inicial · MXN<input name="opening" type="number" min="0" step="0.01" defaultValue={v.opening/100} required/></label><button disabled={busy}>Corregir saldo inicial</button></form></details>
 </>}
 <details className="card"><summary>Cómo funciona el rendimiento</summary><p className="hint">Los gastos desde el {dateLabel(v?.start||today)} se descuentan automáticamente. No registres el mismo pago como gasto y retiro.</p><p className="hint">Cada día completo genera saldo × tasa anual / 365, redondeado a centavos y reinvertido. Los movimientos de una fecha se aplican antes de calcular su rendimiento, que se agrega al día siguiente. Hoy aún no cuenta como día completo. Se recalcula al abrir la app, sin necesitar que quede abierta.</p><p className="hint">Estimación antes de impuestos. No se conecta a Nu ni aplica automáticamente condiciones de Turbo, límites promocionales o retenciones. Registra solo el dinero realmente apartado en tu Cajita. La tasa inicial es el 13% que indicaste; comprueba en Nu la tasa vigente y registra sus cambios. Si el saldo difiere, usa un ajuste al saldo real.</p><a className="hint" href="https://blog.nu.com.mx/productos-nu/cuenta-nu/rendimiento-con-cajita-turbo/" target="_blank" rel="noreferrer">Información oficial de Nu ↗</a></details></>;
}














